services:
  backend:
    command: uvicorn src.main:app --reload --port 8000 --host 0.0.0.0
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      TG_API_TOKEN: ${TG_API_TOKEN}
      VK_API_TOKEN: ${VK_API_TOKEN}
      MAX_API_TOKEN: ${MAX_API_TOKEN}
      VK_BOT_LINK: ${VK_BOT_LINK}
      TG_BOT_LINK: ${TG_BOT_LINK}
      MAX_BOT_LINK: ${MAX_BOT_LINK}
      VERIFY_CHAT_ID: ${VK_VERIFY_CHAT_ID}
      ADMIN_IDS: ${ADMIN_IDS}
      LOG_CHAT: ${LOG_CHAT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FILE: ${LOG_FILE}
      LOG_FORMAT: ${LOG_FORMAT}
      GROUP_ID: ${VK_GROUP_ID}
      SERVICE_TOKEN: ${VK_SERVICE_TOKEN}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      S3_KEY: ${S3_KEY}
      S3_SECRET: ${S3_SECRET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      GROUP_LINK: ${GROUP_LINK}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: always
    ports:
      - '8000:8000'
